version: '3.7'

services:
  app:
    image: anpr
    container_name: anpr
    hostname: anpr
    build:
      context: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/vendor
    stdin_open: true
    tty: true
    command: php artisan serve --host 0.0.0.0 --port 3001
